/* 100 Books on Korea - book data.
   Edit this file to change the list; the page reads it directly.
   Fields: id, author, title, url, category, publisher, source, isbn, cover, blurb
   `cover` may be null, and may 404 - the page falls through to Google
   Books and then to a generated typographic cover. It may also be a
   relative path such as assets/covers/<name>.jpg, which is how you pin a
   book to your own artwork; a path with no file behind it simply falls
   through to the ISBN sources.
   Generated from books.json - keep the two in step. */
window.BOOKS = [
  {
    "id": "troubled-apologies-among-japan-korea-and-the-united-states",
    "author": "Alexis Dudden",
    "title": "Troubled Apologies Among Japan, Korea, and the United States",
    "url": "https://cup.columbia.edu/book/troubled-apologies-among-japan-korea-and-the-united-states/9780231141772",
    "category": "Alliances & Regional Order",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231141772",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231141772-L.jpg?default=false",
    "blurb": "Dudden treats the apology itself as a political act, tracing how expressions of regret between Tokyo, Seoul and Washington have been drafted, hedged, withdrawn and re-read. The result is less a catalogue of grievances than an anatomy of why the region's apologies so rarely settle anything."
  },
  {
    "id": "sovereignty-experiments-korean-migrants-and-the-building-of-",
    "author": "Alyssa M. Park",
    "title": "Sovereignty Experiments: Korean Migrants and the Building of Borders in Northeast Asia, 1860–1945",
    "url": "https://www.cornellpress.cornell.edu/book/9781501738364/sovereignty-experiments/",
    "category": "Diaspora & Migration",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9781501738364",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501738364-L.jpg?default=false",
    "blurb": "Park follows Korean migrants across the Tumen and Yalu into Qing Manchuria and the Russian Far East, and shows three empires improvising rules of belonging around people who kept crossing anyway. Borders here are not lines inherited but claims tested, and the testing is done by the migrants."
  },
  {
    "id": "the-real-north-korea",
    "author": "Andrei Lankov",
    "title": "The Real North Korea",
    "url": "https://global.oup.com/academic/product/the-real-north-korea-9780199390038?cc=us&lang=en&",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Oxford University Press",
    "source": "global.oup.com",
    "isbn": "9780199390038",
    "cover": "assets/covers/the-real-north-korea.jpg",
    "blurb": "Lankov, who studied in Pyongyang, argues the regime is neither irrational nor suicidal but coldly competent at survival. The book is bracing precisely because it takes the leadership's incentives seriously and follows them to uncomfortable conclusions about what outside pressure can and cannot achieve."
  },
  {
    "id": "activists-alliances-and-anti-u-s-base-protests",
    "author": "Andrew Yeo",
    "title": "Activists, Alliances, and Anti-U.S. Base Protests",
    "url": "https://www.cambridge.org/core/books/activists-alliances-and-antius-base-protests/7FB051506DD80F1042FDB25AACD8860D",
    "category": "Alliances & Regional Order",
    "publisher": "Cambridge University Press",
    "source": "cambridge.org",
    "isbn": "9781107002470",
    "cover": "assets/covers/activists-alliances.jpg",
    "blurb": "Yeo asks why anti-base movements succeed in some allied states and stall in others, and finds the answer in the domestic security consensus each movement has to argue against. Comparative, and unusually attentive to the activists' own strategic thinking."
  },
  {
    "id": "kim-jong-un-and-the-bomb",
    "author": "Ankit Panda",
    "title": "Kim Jong Un and the Bomb",
    "url": "https://www.hurstpublishers.com/book/kim-jong-un-and-the-bomb/",
    "category": "North Korea: Nuclear & Security",
    "publisher": "Hurst",
    "source": "hurstpublishers.com",
    "isbn": "9781787383074",
    "cover": "https://covers.openlibrary.org/b/isbn/9781787383074-L.jpg?default=false",
    "blurb": "Panda reconstructs how North Korea went from a marginal proliferation worry to a state credibly able to threaten the American homeland. Strong on the technical detail of the arsenal, and equally on the deterrence logic that makes disarmament a far harder sell than policy debate usually admits."
  },
  {
    "id": "the-great-successor",
    "author": "Anna Fifield",
    "title": "The Great Successor",
    "url": "https://www.hachettebookgroup.com/titles/anna-fifield/the-great-successor/9781541742505/?lens=publicaffairs",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9781541742505",
    "cover": "https://covers.openlibrary.org/b/isbn/9781541742505-L.jpg?default=false",
    "blurb": "Fifield, who covered the peninsula for years, assembles the life of a leader who was widely written off as a placeholder and was not. Reported from defectors, classmates and officials, it is the most human-scale portrait of Kim Jong Un available."
  },
  {
    "id": "to-save-the-children-of-korea-the-cold-war-origins-of-intern",
    "author": "Arissa H. Oh",
    "title": "To Save the Children of Korea: The Cold War Origins of International Adoption",
    "url": "https://www.sup.org/books/asian-american-studies/save-children-korea",
    "category": "Diaspora & Migration",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9780804795326",
    "cover": "https://covers.openlibrary.org/b/isbn/9780804795326-L.jpg?default=false",
    "blurb": "Oh traces the birth of international adoption to the aftermath of the Korean War, where Christian humanitarianism, Cold War politics and race made Korean children uniquely adoptable to American families. It explains how an emergency response hardened into a global system."
  },
  {
    "id": "operation-broken-reed-truman-s-secret-north-korean-spy-missi",
    "author": "Arthur L. Boyd",
    "title": "Operation Broken Reed: Truman's Secret North Korean Spy Mission That Averted World War III",
    "url": "https://www.hachettebookgroup.com/titles/arthur-l-boyd/operation-broken-reed/9780786732616/",
    "category": "Korean War",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9780786732616",
    "cover": "https://covers.openlibrary.org/b/isbn/9780786732616-L.jpg?default=false",
    "blurb": "Boyd's account of a covert intelligence mission behind North Korean lines, told from his father's service record and declassified material. Read it as a participant-adjacent war story rather than settled history; its claims have been contested."
  },
  {
    "id": "the-cleanest-race-how-north-koreans-see-themselves-and-why-i",
    "author": "B.R. Myers",
    "title": "The Cleanest Race: How North Koreans See Themselves and Why It Matters",
    "url": "https://www.barnesandnoble.com/w/the-cleanest-race-b-r-myers/1100410201",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Melville House",
    "source": "barnesandnoble.com",
    "isbn": "9781933633916",
    "cover": "assets/covers/the-cleanest-race.jpg",
    "blurb": "Myers reads North Korean domestic propaganda on its own terms and concludes the state's real ideology is not communism but a paranoid race-based nationalism closer to wartime Japan. Short, argumentative, and one of the few books that changes how you read everything else about the country."
  },
  {
    "id": "i-want-to-die-but-i-want-to-eat-tteokbokki",
    "author": "Baek Sehee",
    "title": "I Want to Die but I Want to Eat Tteokbokki",
    "url": "https://www.bloomsbury.com/us/i-want-to-die-but-i-want-to-eat-tteokbokki-9781639732043/",
    "category": "Fiction & Memoir",
    "publisher": "Bloomsbury",
    "source": "bloomsbury.com",
    "isbn": "9781639732043",
    "cover": "https://covers.openlibrary.org/b/isbn/9781639732043-L.jpg?default=false",
    "blurb": "Baek transcribes her sessions with a psychiatrist over treatment for dysthymia, leaving in the circling and the self-doubt. Its enormous popularity in Korea and abroad says something about how much room there was for a book that treats low-grade despair as ordinary."
  },
  {
    "id": "nothing-to-envy-ordinary-lives-in-north-korea",
    "author": "Barbara Demick",
    "title": "Nothing to Envy: Ordinary Lives in North Korea",
    "url": "https://www.penguinrandomhouse.com/books/39398/nothing-to-envy-by-barbara-demick/",
    "category": "North Korea: Society & Economy",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780385523912",
    "cover": "assets/covers/nothing-to-envy.jpg",
    "blurb": "Demick follows six residents of Chongjin through the famine years, reconstructing their lives from interviews after they escaped. It remains the best book for grasping what the collapse of the 1990s actually did to people, and it reads like a novel."
  },
  {
    "id": "guns-guerillas-and-the-great-leader-north-korea-and-the-thir",
    "author": "Benjamin R. Young",
    "title": "Guns, Guerillas, and the Great Leader: North Korea and the Third World",
    "url": "https://www.sup.org/books/history/guns-guerillas-and-great-leader",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503627635",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503627635-L.jpg?default=false",
    "blurb": "Young recovers North Korea's forgotten career as a Third World patron, sending arms, instructors and construction crews across Africa, the Middle East and Latin America. It reframes a state usually described as hermetic as an ambitious, if overreaching, global actor."
  },
  {
    "id": "escape-from-camp-14",
    "author": "Blaine Harden",
    "title": "Escape from Camp 14",
    "url": "https://www.penguinrandomhouse.com/books/307766/escape-from-camp-14-by-blaine-harden/9780143122913/",
    "category": "Escape & Human Rights",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780143122913",
    "cover": "https://covers.openlibrary.org/b/isbn/9780143122913-L.jpg?default=false",
    "blurb": "Harden tells the story of Shin Dong-hyuk, born inside a political prison camp and later escaped. Parts of the account were revised after Shin corrected his own testimony, which the book's later editions address; it remains a central text on the camp system."
  },
  {
    "id": "the-great-leader-and-the-fighter-pilot",
    "author": "Blaine Harden",
    "title": "The Great Leader and the Fighter Pilot",
    "url": "https://www.penguinrandomhouse.com/books/315267/the-great-leader-and-the-fighter-pilot-by-blaine-harden/",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780143108023",
    "cover": "https://covers.openlibrary.org/b/isbn/9780143108023-L.jpg?default=false",
    "blurb": "Harden braids two lives from the same years: Kim Il Sung consolidating power, and a young North Korean pilot who flew a MiG to the South. The pairing makes the founding of the state legible through the people who had to live inside it or run."
  },
  {
    "id": "the-japan-south-korea-identity-clash-east-asian-security-and",
    "author": "Brad Glosserman and Scott A. Snyder",
    "title": "The Japan–South Korea Identity Clash: East Asian Security and the United States",
    "url": "https://cup.columbia.edu/book/the-japansouth-korea-identity-clash/9780231171717",
    "category": "Alliances & Regional Order",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231171717",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231171717-L.jpg?default=false",
    "blurb": "Glosserman and Snyder argue the recurring rupture between Seoul and Tokyo is not really about any single dispute but about two national identities that keep colliding. Useful for understanding why the relationship resets and then breaks again on schedule."
  },
  {
    "id": "under-the-loving-care-of-the-fatherly-leader-north-korea-and",
    "author": "Bradley K. Martin",
    "title": "Under the Loving Care of the Fatherly Leader: North Korea and the Kim Dynasty",
    "url": "https://us.macmillan.com/books/9781429906999/underthelovingcareofthefatherlyleader/",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Macmillan",
    "source": "us.macmillan.com",
    "isbn": "9781429906999",
    "cover": "https://covers.openlibrary.org/b/isbn/9781429906999-L.jpg?default=false",
    "blurb": "Martin's enormous history of the Kim dynasty, built on decades of reporting and interviews. It is long, but it is the reference volume for how the family built and kept a hereditary state."
  },
  {
    "id": "korea-s-place-in-the-sun-a-modern-history",
    "author": "Bruce Cumings",
    "title": "Korea's Place in the Sun: A Modern History",
    "url": "https://wwnorton.com/books/9780393327021",
    "category": "History & Empire",
    "publisher": "W. W. Norton",
    "source": "wwnorton.com",
    "isbn": "9780393327021",
    "cover": "https://covers.openlibrary.org/b/isbn/9780393327021-L.jpg?default=false",
    "blurb": "Cumings's single-volume modern history, opinionated and beautifully written, insisting Korea be understood on its own terms rather than as an object of great-power policy. The standard starting point, and the one people argue with."
  },
  {
    "id": "the-korean-war-a-history",
    "author": "Bruce Cumings",
    "title": "The Korean War: A History",
    "url": "https://www.penguinrandomhouse.com/books/35571/the-korean-war-by-bruce-cumings/",
    "category": "Korean War",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780812978964",
    "cover": "https://covers.openlibrary.org/b/isbn/9780812978964-L.jpg?default=false",
    "blurb": "Cumings's short revisionist account, more concerned with how the war is remembered and what it did to civilians than with battlefield chronology. Read alongside a conventional military history rather than instead of one."
  },
  {
    "id": "suffering-and-smiling-daily-life-in-north-korea",
    "author": "Byung-Ho Chung",
    "title": "Suffering and Smiling: Daily Life in North Korea",
    "url": "https://rowman.com/ISBN/9781538193853/Suffering-and-Smiling-Daily-Life-in-North-Korea",
    "category": "North Korea: Society & Economy",
    "publisher": "Rowman & Littlefield",
    "source": "rowman.com",
    "isbn": "9781538193853",
    "cover": "https://covers.openlibrary.org/b/isbn/9781538193853-L.jpg?default=false",
    "blurb": "Chung, an anthropologist with unusual field access, looks at how ordinary North Koreans manage daily life under scarcity and surveillance. The value is in the texture: what people do, not what the state says they do."
  },
  {
    "id": "the-park-chung-hee-era-the-transformation-of-south-korea",
    "author": "Byung-Kook Kim and Ezra F. Vogel",
    "title": "The Park Chung Hee Era: The Transformation of South Korea",
    "url": "https://www.hup.harvard.edu/books/9780674072312",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Harvard University Press",
    "source": "hup.harvard.edu",
    "isbn": "9780674072312",
    "cover": "https://covers.openlibrary.org/b/isbn/9780674072312-L.jpg?default=false",
    "blurb": "A large edited volume on the years that made the South Korean economy and its dictatorship at once. Chapters disagree with each other, which is the point — it is the best single place to see the scholarly argument over Park laid out."
  },
  {
    "id": "unveiling-the-north-korean-economy-collapse-and-transition",
    "author": "Byung-Yeon Kim",
    "title": "Unveiling the North Korean Economy: Collapse and Transition",
    "url": "https://www.cambridge.org/core/books/unveiling-the-north-korean-economy/796B9543D8B334BD82B0DD75B84E81BC",
    "category": "North Korea: Society & Economy",
    "publisher": "Cambridge University Press",
    "source": "cambridge.org",
    "isbn": "9781107183797",
    "cover": "https://covers.openlibrary.org/b/isbn/9781107183797-L.jpg?default=false",
    "blurb": "Kim rebuilds North Korean macroeconomic data and pairs it with surveys of refugees and of Chinese firms trading across the border. The most rigorous attempt to put numbers on an economy that publishes almost none."
  },
  {
    "id": "ghost-flames-life-and-death-in-a-hidden-war-korea-1950-1953",
    "author": "Charles J. Hanley",
    "title": "Ghost Flames: Life and Death in a Hidden War, Korea 1950-1953",
    "url": "https://www.amazon.com/Ghost-Flames-Death-Hidden-1950-1953/dp/1541768175",
    "category": "Korean War",
    "publisher": "Amazon",
    "source": "amazon.com",
    "isbn": "9781541768178",
    "cover": "https://covers.openlibrary.org/b/isbn/9781541768178-L.jpg?default=false",
    "blurb": "Hanley, who reported the No Gun Ri killings, tells the war through twenty people on all sides, moving between them chronologically. It restores the civilian experience to a war usually narrated from headquarters."
  },
  {
    "id": "whale",
    "author": "Cheon Myeong-Kwan",
    "title": "Whale",
    "url": "https://www.penguinrandomhouse.com/books/691554/whale-by-cheon-myeong-kwan/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781953861146",
    "cover": "https://covers.openlibrary.org/b/isbn/9781953861146-L.jpg?default=false",
    "blurb": "A sprawling, grotesque, funny novel that follows three characters through the violent modernisation of postwar Korea. Shortlisted for the International Booker, and unlike anything else on this shelf in register."
  },
  {
    "id": "kim-jiyoung-born-1982",
    "author": "Cho Nam-Joo",
    "title": "Kim Jiyoung, Born 1982",
    "url": "https://www.simonandschuster.co.uk/books/Kim-Jiyoung-Born-1982/Cho-Nam-Joo/9781471184307",
    "category": "Fiction & Memoir",
    "publisher": "Simon & Schuster",
    "source": "simonandschuster.co.uk",
    "isbn": "9781471184307",
    "cover": "https://covers.openlibrary.org/b/isbn/9781471184307-L.jpg?default=false",
    "blurb": "Cho's flatly narrated novel about an ordinary Korean woman's life became a lightning rod in Korea's gender debate. Its power is the deadpan accumulation of small, documented indignities rather than any single dramatic turn."
  },
  {
    "id": "figuring-korean-futures-children-s-literature-in-modern-kore",
    "author": "Dafna Zur",
    "title": "Figuring Korean Futures: Children's Literature in Modern Korea",
    "url": "https://www.sup.org/books/asian-studies/figuring-korean-futures",
    "category": "Culture & the Korean Wave",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503601680",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503601680-L.jpg?default=false",
    "blurb": "Zur shows how writing for children became a place where colonial and postcolonial Korea worked out what kind of nation it wanted. The child, she argues, was the figure through which modernity was imagined and disciplined."
  },
  {
    "id": "north-korea-confidential",
    "author": "Daniel Tudor and James Pearson",
    "title": "North Korea Confidential",
    "url": "https://www.tuttlepublishing.com/korea/north-korea-confidential",
    "category": "North Korea: Society & Economy",
    "publisher": "Tuttle",
    "source": "tuttlepublishing.com",
    "isbn": "9780804852265",
    "cover": "https://covers.openlibrary.org/b/isbn/9780804852265-L.jpg?default=false",
    "blurb": "Tudor and Pearson assemble what daily life in North Korea actually looks like — private markets, smuggled media, fashion, bribery, the real price of things. Brisk, concrete, and the best corrective to the parade-ground image."
  },
  {
    "id": "contentious-activism-and-inter-korean-relations",
    "author": "Danielle L. Chubb",
    "title": "Contentious Activism and Inter-Korean Relations",
    "url": "https://cup.columbia.edu/book/contentious-activism-and-interkorean-relations/9780231161367",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231161367",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231161367-L.jpg?default=false",
    "blurb": "Chubb examines how South Korean activists on both left and right shaped what could be said about the North, and therefore what governments could do. A reminder that Seoul's North Korea policy has a domestic constituency."
  },
  {
    "id": "the-coldest-winter-america-and-the-korean-war",
    "author": "David Halberstam",
    "title": "The Coldest Winter: America and the Korean War",
    "url": "https://www.hachettebookgroup.com/titles/david-halberstam/the-coldest-winter/9781401389642/?lens=hachette-books",
    "category": "Korean War",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9781401389642",
    "cover": "https://covers.openlibrary.org/b/isbn/9781401389642-L.jpg?default=false",
    "blurb": "Halberstam's last book, a narrative history centred on the Chinese intervention and the collision between MacArthur and Washington. Journalistic, character-driven, and the most readable American account of the war."
  },
  {
    "id": "the-two-koreas",
    "author": "Don Oberdorfer & Robert Carlin",
    "title": "The Two Koreas",
    "url": "https://www.hachettebookgroup.com/titles/don-oberdorfer/the-two-koreas/9780465031238/?lens=basic-books",
    "category": "Alliances & Regional Order",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9780465031238",
    "cover": "https://covers.openlibrary.org/b/isbn/9780465031238-L.jpg?default=false",
    "blurb": "Oberdorfer's history of the peninsula since the 1970s, updated with Robert Carlin, drawing on the diplomacy both men watched at close range. If you read one book on how the two Koreas and Washington actually negotiated, this is it."
  },
  {
    "id": "flawless-lessons-in-looks-and-culture-from-the-k-beauty-capi",
    "author": "Elise Hu",
    "title": "Flawless: Lessons in Looks and Culture from the K-Beauty Capital",
    "url": "https://www.penguinrandomhouse.com/books/667034/flawless-by-elise-hu/",
    "category": "Culture & the Korean Wave",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780593184189",
    "cover": "https://covers.openlibrary.org/b/isbn/9780593184189-L.jpg?default=false",
    "blurb": "Hu, formerly NPR's Seoul bureau chief, reports on the K-beauty industry and what living inside it did to her own sense of appearance. Part memoir, part investigation of an export industry built on impossible standards."
  },
  {
    "id": "korea-a-history",
    "author": "Eugene Y. Park",
    "title": "Korea: A History",
    "url": "https://www.sup.org/books/asian-studies/korea",
    "category": "History & Empire",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503629844",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503629844-L.jpg?default=false",
    "blurb": "Park's accessible single-volume history from antiquity to the present, unusually attentive to daily life, ethnic minorities, LGBTQ history and the North. A good modern alternative to the older survey texts."
  },
  {
    "id": "the-birth-of-korean-cool",
    "author": "Euny Hong",
    "title": "The Birth of Korean Cool",
    "url": "https://us.macmillan.com/books/9781250045119/thebirthofkoreancool/",
    "category": "Culture & the Korean Wave",
    "publisher": "Macmillan",
    "source": "us.macmillan.com",
    "isbn": "9781250045119",
    "cover": "https://covers.openlibrary.org/b/isbn/9781250045119-L.jpg?default=false",
    "blurb": "Hong's early, breezy account of how a country decided to manufacture cultural influence and largely succeeded. Written before the Korean Wave was a given, which is what makes it interesting now."
  },
  {
    "id": "if-i-had-your-face",
    "author": "Frances Cha",
    "title": "If I Had Your Face",
    "url": "https://www.penguinrandomhouse.com/books/610610/if-i-had-your-face-by-frances-cha/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780593129487",
    "cover": "https://covers.openlibrary.org/b/isbn/9780593129487-L.jpg?default=false",
    "blurb": "Cha's novel follows four young women sharing a Seoul apartment building, through plastic surgery, room salons and precarious work. It is about what beauty costs when it is the most liquid asset you have."
  },
  {
    "id": "accidental-tyrant",
    "author": "Fyodor Tertitskiy",
    "title": "Accidental Tyrant: The Life of Kim Il-sung",
    "url": "https://www.hurstpublishers.com/book/accidental-tyrant/",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Hurst",
    "source": "hurstpublishers.com",
    "isbn": "9781911723547",
    "cover": "https://covers.openlibrary.org/b/isbn/9781911723547-L.jpg?default=false",
    "blurb": "Tertitskiy works from Korean, Russian, Chinese and Japanese sources to replace the guerrilla legend with a working politician: a junior Soviet officer who was installed rather than risen, who then out-manoeuvred every faction that had a better claim, prised Pyongyang loose from Moscow, ran the economy into famine, and built the only hereditary succession communism ever produced. The title is the argument — almost nothing about the man was inevitable. A Financial Times best history book of 2025."
  },
  {
    "id": "the-lazarus-heist",
    "author": "Geoff White",
    "title": "The Lazarus Heist",
    "url": "https://www.penguin.co.uk/books/447163/the-lazarus-heist-by-white-geoff/9780241554272",
    "category": "North Korea: Nuclear & Security",
    "publisher": "Penguin",
    "source": "penguin.co.uk",
    "isbn": "9780241554272",
    "cover": "assets/covers/the-lazarus-heist.jpg",
    "blurb": "White's account of North Korea's state hacking operation, from the Sony breach to bank thefts and cryptocurrency raids. It makes the case that the regime's most effective weapons programme may be the one on the network."
  },
  {
    "id": "samsung-rising",
    "author": "Geoffrey Cain",
    "title": "Samsung Rising: The Inside Story of the South Korean Giant That Set Out to Beat Apple and Conquer Tech",
    "url": "https://www.penguinrandomhouse.com/books/537977/samsung-rising-by-geoffrey-cain/",
    "category": "South Korea: Society & Economy",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780593236703",
    "cover": "https://covers.openlibrary.org/b/isbn/9780593236703-L.jpg?default=false",
    "blurb": "Cain covered Samsung from Seoul for the Economist, the Wall Street Journal and Time, and this is an unauthorised corporate biography: the sugar-and-fertiliser conglomerate that bet everything on memory chips, the chairman who had employees pile up and burn 150,000 defective phones, and the succession and bribery cases that ran all the way into the Blue House. The clearest account in English of how one family firm came to carry a national economy."
  },
  {
    "id": "south-korea-s-democracy-in-crisis-the-threats-of-illiberalis",
    "author": "Gi-Wook Shin and Ho-Ki Kim",
    "title": "South Korea's Democracy in Crisis: The Threats of Illiberalism, Populism, and Polarization",
    "url": "https://www.sup.org/books/south-koreas-democracy-crisis",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781538177815",
    "cover": "https://covers.openlibrary.org/b/isbn/9781538177815-L.jpg?default=false",
    "blurb": "An edited volume on polarisation, populism and illiberal drift in a democracy usually held up as a success story. Prescient given what followed, and unsparing about both camps."
  },
  {
    "id": "privilege-and-anxiety-the-korean-middle-class-in-the-global-",
    "author": "Hagen Koo",
    "title": "Privilege and Anxiety: The Korean Middle Class in the Global Era",
    "url": "https://www.cornellpress.cornell.edu/book/9781501764943/privilege-and-anxiety/",
    "category": "South Korea: Society & Economy",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9781501764943",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501764943-L.jpg?default=false",
    "blurb": "Koo examines a middle class that got everything it was promised and is terrified of losing it — in housing, education and the scramble to reproduce its own status. The best sociological account of why Korean life feels like a competition."
  },
  {
    "id": "on-desperate-ground-the-epic-story-of-chosin-reservoir-the-g",
    "author": "Hampton Sides",
    "title": "On Desperate Ground: The Epic Story of Chosin Reservoir—the Greatest Battle of the Korean War",
    "url": "https://www.penguinrandomhouse.com/books/534710/on-desperate-ground-by-hampton-sides/",
    "category": "Korean War",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781101971215",
    "cover": "https://covers.openlibrary.org/b/isbn/9781101971215-L.jpg?default=false",
    "blurb": "Sides's narrative of the Chosin Reservoir campaign and the Marines' fighting withdrawal in appalling cold. Pure battle history, superbly paced."
  },
  {
    "id": "the-vegetarian",
    "author": "Han Kang",
    "title": "The Vegetarian",
    "url": "https://www.penguinrandomhouse.com/books/250333/the-vegetarian-by-han-kang/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781101906118",
    "cover": "https://covers.openlibrary.org/b/isbn/9781101906118-L.jpg?default=false",
    "blurb": "Han's novel begins with a woman who simply stops eating meat and follows the violence her refusal provokes in everyone around her. Winner of the International Booker, and the book that opened Korean fiction to a wide English readership."
  },
  {
    "id": "flowers-of-fire",
    "author": "Hawon Jung",
    "title": "Flowers of Fire",
    "url": "https://www.penguinrandomhouse.com/books/718956/flowers-of-fire-by-hawon-jung/",
    "category": "South Korea: Society & Economy",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781637742419",
    "cover": "https://covers.openlibrary.org/b/isbn/9781637742419-L.jpg?default=false",
    "blurb": "Jung, a longtime wire correspondent, reports the rise of South Korea's feminist movement through the spycam protests, #MeToo cases and the backlash. Journalism written close to the people who took the risks."
  },
  {
    "id": "welcome-to-the-hyunam-dong-bookshop",
    "author": "Hwang Bo-reum",
    "title": "Welcome to the Hyunam-dong Bookshop",
    "url": "https://www.bloomsbury.com/us/welcome-to-the-hyunamdong-bookshop-9781639732425/",
    "category": "Fiction & Memoir",
    "publisher": "Bloomsbury",
    "source": "bloomsbury.com",
    "isbn": "9781639732425",
    "cover": "https://covers.openlibrary.org/b/isbn/9781639732425-L.jpg?default=false",
    "blurb": "A gentle novel about a woman who quits her career to open a neighbourhood bookshop and the people who drift into it. The flagship of Korea's healing-fiction wave, and a deliberate rest from the rest of this shelf."
  },
  {
    "id": "gwangju-uprising-the-rebellion-for-democracy-in-south-korea",
    "author": "Hwang Sok-yong, Lee Jae-Eui and Jeon Yong-Ho",
    "title": "Gwangju Uprising: The Rebellion for Democracy in South Korea",
    "url": "https://www.penguinrandomhouse.com/books/697249/gwangju-uprising-by-hwang-sok-yong-lee-jae-eui-and-jeon-yong-ho/",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781788737142",
    "cover": "https://covers.openlibrary.org/b/isbn/9781788737142-L.jpg?default=false",
    "blurb": "The classic eyewitness compilation of the 1980 Gwangju uprising and its suppression, newly translated, with a preface by Hwang Sok-yong. It circulated underground for years; it is the founding document of South Korea's democratic memory."
  },
  {
    "id": "the-girl-with-seven-names-escape-from-north-korea",
    "author": "Hyeonseo Lee",
    "title": "The Girl with Seven Names: Escape from North Korea",
    "url": "https://www.harpercollins.com/products/the-girl-with-seven-names-escape-from-north-korea-hyeonseo-lee?variant=32173126647842",
    "category": "Escape & Human Rights",
    "publisher": "HarperCollins",
    "source": "harpercollins.com",
    "isbn": "9780007554843",
    "cover": "https://covers.openlibrary.org/b/isbn/9780007554843-L.jpg?default=false",
    "blurb": "Lee's memoir of leaving North Korea at seventeen, the decade of concealment in China that followed, and getting her family out. Strong on the part most escape narratives skip: what happens after the border."
  },
  {
    "id": "contested-embrace-transborder-membership-politics-in-twentie",
    "author": "Jaeeun Kim",
    "title": "Contested Embrace: Transborder Membership Politics in Twentieth-Century Korea",
    "url": "https://www.sup.org/books/asian-studies/contested-embrace",
    "category": "Diaspora & Migration",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9780804797627",
    "cover": "https://covers.openlibrary.org/b/isbn/9780804797627-L.jpg?default=false",
    "blurb": "Kim asks who counts as Korean, following colonial-era migrants to Japan and China and the two postwar states' competing claims on them. A sharp study of citizenship as something states grant, withhold and weaponise."
  },
  {
    "id": "a-corpse-in-the-koryo",
    "author": "James Church",
    "title": "A Corpse in the Koryo",
    "url": "https://us.macmillan.com/books/9780312374310/acorpseinthekoryo/",
    "category": "Fiction & Memoir",
    "publisher": "Macmillan",
    "source": "us.macmillan.com",
    "isbn": "9780312374310",
    "cover": "https://covers.openlibrary.org/b/isbn/9780312374310-L.jpg?default=false",
    "blurb": "The first Inspector O novel, written under a pseudonym by a former Western intelligence officer. The plot is a police procedural; the reason to read it is the atmosphere of working inside a system where no one can be told the truth."
  },
  {
    "id": "dear-leader-my-escape-from-north-korea",
    "author": "Jang Jin-sung",
    "title": "Dear Leader: My Escape from North Korea",
    "url": "https://www.simonandschuster.com/books/Dear-Leader/Jang-Jin-sung/9781476766560",
    "category": "Escape & Human Rights",
    "publisher": "Simon & Schuster",
    "source": "simonandschuster.com",
    "isbn": "9781476766560",
    "cover": "https://covers.openlibrary.org/b/isbn/9781476766560-L.jpg?default=false",
    "blurb": "Jang wrote propaganda for Kim Jong Il's court before fleeing. The value is the vantage point — an insider's view of how the regime manufactures its own myth, followed by an escape narrative."
  },
  {
    "id": "the-2020-commission-report-on-the-north-korean-nuclear-attac",
    "author": "Jeffrey Lewis",
    "title": "The 2020 Commission Report on the North Korean Nuclear Attacks Against the United States: A Speculative Novel",
    "url": "https://www.harpercollins.com/products/the-2020-commission-report-on-the-north-korean-nuclear-attacks-against-the-us-jeffrey-lewis?variant=39934995922978",
    "category": "Fiction & Memoir",
    "publisher": "HarperCollins",
    "source": "harpercollins.com",
    "isbn": "9781328573919",
    "cover": "https://covers.openlibrary.org/b/isbn/9781328573919-L.jpg?default=false",
    "blurb": "Lewis, a nonproliferation analyst, writes a speculative novel in the form of an official commission report into a nuclear exchange. It is fiction built entirely from real systems and real doctrine, which is what makes it frightening."
  },
  {
    "id": "china-s-hegemony-four-hundred-years-of-east-asian-domination",
    "author": "Ji-Young Lee",
    "title": "China's Hegemony: Four Hundred Years of East Asian Domination",
    "url": "https://cup.columbia.edu/book/chinas-hegemony/9780231179744",
    "category": "History & Empire",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231179744",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231179744-L.jpg?default=false",
    "blurb": "Lee asks why Korea and others accepted Chinese primacy for centuries, and argues the answer lies in legitimacy and domestic politics rather than raw coercion. Directly relevant to current arguments about what Chinese regional power would look like."
  },
  {
    "id": "north-korea-s-hidden-revolution-how-the-information-undergro",
    "author": "Jieun Baek",
    "title": "North Korea's Hidden Revolution: How the Information Underground Is Transforming a Closed Society",
    "url": "https://yalebooks.yale.edu/book/9780300217810/north-koreas-hidden-revolution/",
    "category": "North Korea: Society & Economy",
    "publisher": "Yale University Press",
    "source": "yalebooks.yale.edu",
    "isbn": "9780300217810",
    "cover": "https://covers.openlibrary.org/b/isbn/9780300217810-L.jpg?default=false",
    "blurb": "Baek documents the smuggling of foreign films, dramas and news into North Korea, and argues that outside information is quietly eroding the state's monopoly on reality. Built on interviews with the people who moved the files."
  },
  {
    "id": "the-hard-road-out-one-woman-s-escape-from-north-korea",
    "author": "Jihyun Park and Seh-Lynn Chai",
    "title": "The Hard Road Out: One Woman's Escape From North Korea",
    "url": "https://www.harpercollins.com/products/the-hard-road-out-one-womans-escape-from-north-korea-jihyun-parkseh-lynn-chai?variant=40299088969762",
    "category": "Escape & Human Rights",
    "publisher": "HarperCollins",
    "source": "harpercollins.com",
    "isbn": "9780008541408",
    "cover": "https://covers.openlibrary.org/b/isbn/9780008541408-L.jpg?default=false",
    "blurb": "Park escaped North Korea twice, was trafficked into rural China in between, and eventually resettled in Britain. Written with Seh-Lynn Chai, a South Korean who had to confront her own assumptions to hear it."
  },
  {
    "id": "seeds-of-mobilization-the-authoritarian-roots-of-south-korea",
    "author": "Joan E. Cho",
    "title": "Seeds of Mobilization: The Authoritarian Roots of South Korea's Democracy",
    "url": "https://press.umich.edu/Books/S/Seeds-of-Mobilization2",
    "category": "South Korea: Politics & Democracy",
    "publisher": "University of Michigan Press",
    "source": "press.umich.edu",
    "isbn": "9780472056606",
    "cover": "https://covers.openlibrary.org/b/isbn/9780472056606-L.jpg?default=false",
    "blurb": "Cho shows that the industrial complexes and universities the dictatorship built to secure itself became the infrastructure of the movement that brought it down. Development as a double-edged sword, argued with original protest data."
  },
  {
    "id": "korean-messiah",
    "author": "Jonathan Cheng",
    "title": "Korean Messiah: Kim Il Sung and the Christian Roots of North Korea's Personality Cult",
    "url": "https://www.penguinrandomhouse.com/books/558235/korean-messiah-by-jonathan-cheng/",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781524733490",
    "cover": "https://covers.openlibrary.org/b/isbn/9781524733490-L.jpg?default=false",
    "blurb": "Cheng, the Wall Street Journal's former Korea bureau chief, traces the Kim cult back to the American Presbyterian missionaries who made Pyongyang the “Jerusalem of the East” and to Kim Il Sung's own devoutly Christian parents. The claim is that Kimilsungism borrowed its grammar from the faith it displaced — the confession, the hymn, the personal saviour — which makes the regime's endurance look less like Stalinism than like a church. Longlisted for the 2026 Cundill History Prize."
  },
  {
    "id": "under-the-same-sky-from-starvation-in-north-korea-to-salvati",
    "author": "Joseph Kim",
    "title": "Under the Same Sky: From Starvation in North Korea to Salvation in America",
    "url": "https://www.harperacademic.com/book/9780544705272/under-the-same-sky/",
    "category": "Escape & Human Rights",
    "publisher": "HarperCollins",
    "source": "harperacademic.com",
    "isbn": "9780544705272",
    "cover": "https://covers.openlibrary.org/b/isbn/9780544705272-L.jpg?default=false",
    "blurb": "Kim's memoir of homelessness and hunger as a boy during the famine, escape into China, and resettlement in the United States. Unsentimental about how long the aftermath lasts."
  },
  {
    "id": "border-of-water-and-ice-the-yalu-river-and-japan-s-empire-in",
    "author": "Joseph Seeley",
    "title": "Border of Water and Ice: The Yalu River and Japan's Empire in Korea and Manchuria",
    "url": "https://www.cornellpress.cornell.edu/book/9781501777370/border-of-water-and-ice/",
    "category": "History & Empire",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9781501777370",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501777370-L.jpg?default=false",
    "blurb": "Seeley writes the environmental history of the Yalu — its timber, its ice, its floods — and shows how a river resisted the empire trying to administer it. An unusual and rewarding angle on Japanese rule."
  },
  {
    "id": "becoming-kim-jong-un",
    "author": "Jung Pak",
    "title": "Becoming Kim Jong Un",
    "url": "https://www.penguinrandomhouse.com/books/604727/becoming-kim-jong-un-by-jung-h-pak/",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781984819727",
    "cover": "https://covers.openlibrary.org/b/isbn/9781984819727-L.jpg?default=false",
    "blurb": "Pak, a former CIA analyst on North Korea, writes the leader as the intelligence community came to understand him. The interest is as much in how such assessments get made as in the conclusions."
  },
  {
    "id": "a-most-enterprising-country-north-korea-in-the-global-econom",
    "author": "Justin V. Hastings",
    "title": "A Most Enterprising Country: North Korea in the Global Economy",
    "url": "https://www.cornellpress.cornell.edu/book/9781501704901/a-most-enterprising-country/",
    "category": "North Korea: Society & Economy",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9781501704901",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501704901-L.jpg?default=false",
    "blurb": "Hastings traces the networks — licit, illicit and in between — that connect North Korea to the world economy through brokers, shipping and shell companies. It explains why sanctions leak where they leak."
  },
  {
    "id": "the-aquariums-of-pyongyang-ten-years-in-the-north-korean-gul",
    "author": "Kang Chol-Hwan",
    "title": "The Aquariums of Pyongyang: Ten Years in the North Korean Gulag",
    "url": "https://www.hachettebookgroup.com/titles/chol-hwan-kang/the-aquariums-of-pyongyang/9780465004713/?lens=basic-books",
    "category": "Escape & Human Rights",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9780465004713",
    "cover": "https://covers.openlibrary.org/b/isbn/9780465004713-L.jpg?default=false",
    "blurb": "Kang was sent to Yodok as a child and spent ten years there. The first major camp survivor testimony to reach the West, and still one of the most important."
  },
  {
    "id": "please-look-after-mom",
    "author": "Kyung-Sook Shin",
    "title": "Please Look After Mom",
    "url": "https://www.penguinrandomhouse.com/books/203116/please-look-after-mom-by-kyung-sook-shin/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780307739513",
    "cover": "https://covers.openlibrary.org/b/isbn/9780307739513-L.jpg?default=false",
    "blurb": "Shin's novel opens with an elderly woman lost in Seoul Station and circles the family who failed to notice her disappearing long before. A bestseller in Korea and abroad, and quietly devastating on filial debt."
  },
  {
    "id": "a-river-in-darkness-one-man-s-escape-from-north-korea",
    "author": "Masaji Ishikawa",
    "title": "A River in Darkness: One Man's Escape from North Korea",
    "url": "https://www.barnesandnoble.com/w/a-river-in-darkness-masaji-ishikawa/1126160014",
    "category": "Escape & Human Rights",
    "publisher": "Barnes & Noble",
    "source": "barnesandnoble.com",
    "isbn": "9781542047197",
    "cover": "https://covers.openlibrary.org/b/isbn/9781542047197-L.jpg?default=false",
    "blurb": "Ishikawa was born in Japan and taken to North Korea as a boy in the repatriation campaign, then spent decades trying to get back. Bleak and unconsoling, and valuable for documenting a chapter most accounts omit."
  },
  {
    "id": "the-korean-war-ridgway",
    "author": "Matthew B. Ridgway",
    "title": "The Korean War",
    "url": "https://www.hachettebookgroup.com/titles/matthew-b-ridgway/the-korean-war/9780306802676/?lens=hachette-books",
    "category": "Korean War",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9780306802676",
    "cover": "https://covers.openlibrary.org/b/isbn/9780306802676-L.jpg?default=false",
    "blurb": "Ridgway commanded the Eighth Army after the Chinese intervention and then all UN forces. His account is a commander's own assessment of how a collapsing front was stabilised, with the judgements of someone who had to make them."
  },
  {
    "id": "the-korean-war-hastings",
    "author": "Max Hastings",
    "title": "The Korean War",
    "url": "https://www.simonandschuster.com/books/Korean-War/Max-Hastings/9781501131905",
    "category": "Korean War",
    "publisher": "Simon & Schuster",
    "source": "simonandschuster.com",
    "isbn": "9781501131905",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501131905-L.jpg?default=false",
    "blurb": "Hastings's one-volume narrative history, drawing on interviews with veterans from several of the combatant nations. The conventional starting point for the military and diplomatic story."
  },
  {
    "id": "supercorporate-distinction-and-participation-in-post-hierarc",
    "author": "Michael M. Prentice",
    "title": "Supercorporate: Distinction and Participation in Post-Hierarchy South Korea",
    "url": "https://www.sup.org/books/asian-studies/supercorporate",
    "category": "South Korea: Society & Economy",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503631878",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503631878-L.jpg?default=false",
    "blurb": "Prentice's ethnography inside a Korean conglomerate watches managers try to flatten hierarchy without losing status. A rare close-up of the white-collar world that so much Korean social anxiety is organised around."
  },
  {
    "id": "crying-in-h-mart",
    "author": "Michelle Zauner",
    "title": "Crying in H Mart",
    "url": "https://www.penguinrandomhouse.com/books/612676/crying-in-h-mart-by-michelle-zauner/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780525657743",
    "cover": "https://covers.openlibrary.org/b/isbn/9780525657743-L.jpg?default=false",
    "blurb": "Zauner's memoir of her mother's illness and death, and of using Korean food to hold onto a half-inherited identity. It became a phenomenon because the grief is specific rather than universal."
  },
  {
    "id": "pachinko",
    "author": "Min Jin Lee",
    "title": "Pachinko",
    "url": "https://www.hachettebookgroup.com/titles/min-jin-lee/pachinko-national-book-award-finalist/9781455569496/?lens=grand-central-publishing",
    "category": "Fiction & Memoir",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9781455569496",
    "cover": "https://covers.openlibrary.org/b/isbn/9781455569496-L.jpg?default=false",
    "blurb": "Lee's multigenerational novel follows a Korean family in Japan across most of the twentieth century, through occupation, war and permanent second-class status. The best-known fictional treatment of the Zainichi experience."
  },
  {
    "id": "the-interrogation-rooms-of-the-korean-war-the-untold-history",
    "author": "Monica Kim",
    "title": "The Interrogation Rooms of the Korean War: The Untold History",
    "url": "https://press.princeton.edu/books/paperback/9780691210421/the-interrogation-rooms-of-the-korean-war",
    "category": "Korean War",
    "publisher": "Princeton University Press",
    "source": "press.princeton.edu",
    "isbn": "9780691210421",
    "cover": "https://covers.openlibrary.org/b/isbn/9780691210421-L.jpg?default=false",
    "blurb": "Kim relocates the war to the POW camps and interrogation rooms, where prisoners were made to choose sides and the choosing became the war's central political question. Original, archivally deep, and quietly furious."
  },
  {
    "id": "the-making-of-minjung-democracy-and-the-politics-of-represen",
    "author": "Namhee Lee",
    "title": "The Making of Minjung: Democracy and the Politics of Representation in South Korea",
    "url": "https://www.cornellpress.cornell.edu/book/9780801475733/the-making-of-minjung/",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9780801475733",
    "cover": "https://covers.openlibrary.org/b/isbn/9780801475733-L.jpg?default=false",
    "blurb": "Lee examines how South Korean intellectuals constructed 'the people' as a political subject, and what that construction included and left out. Essential for understanding the democratisation movement's own self-image."
  },
  {
    "id": "shrimp-to-whale-south-korea-from-the-forgotten-war-to-k-pop",
    "author": "Ramon Pacheco Pardo",
    "title": "Shrimp to Whale: South Korea from the Forgotten War to K-Pop",
    "url": "https://global.oup.com/academic/product/shrimp-to-whale-9780197764930?cc=us&lang=en&",
    "category": "History & Empire",
    "publisher": "Oxford University Press",
    "source": "global.oup.com",
    "isbn": "9780197764930",
    "cover": "https://covers.openlibrary.org/b/isbn/9780197764930-L.jpg?default=false",
    "blurb": "Pacheco Pardo's brisk narrative of how a ruined country became a cultural and economic power. The most approachable recent one-volume account of the South Korean ascent."
  },
  {
    "id": "patterns-of-impunity-human-rights-in-north-korea-and-the-rol",
    "author": "Robert R. King",
    "title": "Patterns of Impunity: Human Rights in North Korea and the Role of the U.S. Special Envoy",
    "url": "https://www.sup.org/books/patterns-impunity",
    "category": "Escape & Human Rights",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781931368629",
    "cover": "https://covers.openlibrary.org/b/isbn/9781931368629-L.jpg?default=false",
    "blurb": "King served as US special envoy for North Korean human rights and writes from inside the job. Valuable for what it shows about the machinery, and the limits, of human rights diplomacy."
  },
  {
    "id": "north-korea-kidnapped-my-daughter",
    "author": "Sakie Yokota",
    "title": "North Korea Kidnapped My Daughter",
    "url": "https://www.penguinrandomhouse.com/books/194965/north-korea-kidnapped-my-daughter-by-sakie-yokota/",
    "category": "Escape & Human Rights",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9781934287446",
    "cover": "https://covers.openlibrary.org/b/isbn/9781934287446-L.jpg?default=false",
    "blurb": "Yokota's account of her daughter Megumi, abducted from a Japanese street at thirteen, and the decades of campaigning that followed. The abductions as one family lived them."
  },
  {
    "id": "marching-through-suffering-loss-and-survival-in-north-korea",
    "author": "Sandra Fahy",
    "title": "Marching Through Suffering: Loss and Survival in North Korea",
    "url": "https://cup.columbia.edu/book/marching-through-suffering/9780231171359",
    "category": "Escape & Human Rights",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231171359",
    "cover": "assets/covers/marching-through-suffering.jpg",
    "blurb": "Fahy analyses how North Koreans talk about the famine — the euphemisms, silences and self-blame in their own testimony. A careful study of what survivors can and cannot say."
  },
  {
    "id": "south-korea-at-the-crossroads-autonomy-and-alliance-in-an-er",
    "author": "Scott A. Snyder",
    "title": "South Korea at the Crossroads: Autonomy and Alliance in an Era of Rival Powers",
    "url": "https://cup.columbia.edu/book/south-korea-at-the-crossroads/9780231185493",
    "category": "Alliances & Regional Order",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231185493",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231185493-L.jpg?default=false",
    "blurb": "Snyder frames South Korean foreign policy as a long oscillation between autonomy and alliance, and asks where US–China rivalry leaves that choice. The clearest statement of the strategic dilemma facing Seoul."
  },
  {
    "id": "korean-endgame-a-strategy-for-reunification-and-u-s-disengag",
    "author": "Selig S. Harrison",
    "title": "Korean Endgame: A Strategy for Reunification and U.S. Disengagement",
    "url": "https://press.princeton.edu/books/paperback/9780691116266/korean-endgame",
    "category": "Alliances & Regional Order",
    "publisher": "Princeton University Press",
    "source": "press.princeton.edu",
    "isbn": "9780691116266",
    "cover": "https://covers.openlibrary.org/b/isbn/9780691116266-L.jpg?default=false",
    "blurb": "Harrison's argument, from decades of reporting and access in Pyongyang, for phased US disengagement and Korean-led reunification. A minority position, argued at length by someone who had been in the room."
  },
  {
    "id": "civic-activism-in-south-korea",
    "author": "Seungsook Moon",
    "title": "Civic Activism in South Korea",
    "url": "https://cup.columbia.edu/book/civic-activism-in-south-korea/9780231211499",
    "category": "South Korea: Politics & Democracy",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231211499",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231211499-L.jpg?default=false",
    "blurb": "Moon and her contributors examine the NGOs, unions and citizens' groups that filled the space after democratisation. Useful for seeing how a movement culture turned into institutions, and what it lost doing so."
  },
  {
    "id": "politics-of-the-north-korean-diaspora",
    "author": "Sheena Chestnut Greitens",
    "title": "Politics of the North Korean Diaspora",
    "url": "https://www.cambridge.org/core/elements/abs/politics-of-the-north-korean-diaspora/8E00C18DAD49699A9CD3D923F4683FED",
    "category": "Diaspora & Migration",
    "publisher": "Cambridge University Press",
    "source": "cambridge.org",
    "isbn": "9781009197281",
    "cover": "https://covers.openlibrary.org/b/isbn/9781009197281-L.jpg?default=false",
    "blurb": "Greitens traces the emergence of a globally dispersed North Korean émigré population and argues the home regime's authoritarian character shapes diaspora politics far from its borders. Short, and conceptually sharp."
  },
  {
    "id": "the-other-great-game-the-opening-of-korea-and-the-birth-of-m",
    "author": "Sheila Miyoshi Jager",
    "title": "The Other Great Game: The Opening of Korea and the Birth of Modern East Asia",
    "url": "https://www.hup.harvard.edu/books/9780674983397",
    "category": "History & Empire",
    "publisher": "Harvard University Press",
    "source": "hup.harvard.edu",
    "isbn": "9780674983397",
    "cover": "https://covers.openlibrary.org/b/isbn/9780674983397-L.jpg?default=false",
    "blurb": "Jager retells the late nineteenth-century scramble over Korea as a contest that made modern East Asia, with Korea as the prize rather than the bystander. Sweeping diplomatic history, and a corrective to Korea's usual walk-on role."
  },
  {
    "id": "hinge-points-an-inside-look-at-north-korea-s-nuclear-program",
    "author": "Siegfried S. Hecker with Elliot A. Serbin",
    "title": "Hinge Points: An Inside Look at North Korea's Nuclear Program",
    "url": "https://www.sup.org/books/politics/hinge-points",
    "category": "North Korea: Nuclear & Security",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503634459",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503634459-L.jpg?default=false",
    "blurb": "Hecker, the nuclear scientist repeatedly invited to inspect North Korean facilities, walks through what he saw and the decision points where he believes the programme could have been slowed. Uniquely authoritative on the technical side, and pointed about American choices."
  },
  {
    "id": "k-culture-k-pop-cuisine-on-screen-and-more-celebrating-the-k",
    "author": "Simon Clair",
    "title": "K Culture: K-pop, Cuisine, On Screen, And More – Celebrating The Korean Wave",
    "url": "https://www.barnesandnoble.com/w/k-culture-simon-clair/1142973700",
    "category": "Culture & the Korean Wave",
    "publisher": "Barnes & Noble",
    "source": "barnesandnoble.com",
    "isbn": "9781837830879",
    "cover": "https://covers.openlibrary.org/b/isbn/9781837830879-L.jpg?default=false",
    "blurb": "An illustrated survey of the Korean Wave across music, film, television and food. A gift-shelf overview rather than analysis, and useful as an entry point."
  },
  {
    "id": "boundless-winds-of-empire-rhetoric-and-ritual-in-early-choso",
    "author": "Sixiang Wang",
    "title": "Boundless Winds of Empire: Rhetoric and Ritual in Early Choson Diplomacy with Ming China",
    "url": "https://cup.columbia.edu/book/boundless-winds-of-empire/9780231205474",
    "category": "History & Empire",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231205474",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231205474-L.jpg?default=false",
    "blurb": "Wang shows early Chosŏn diplomats using rhetoric, ritual and scholarship to manage Ming China from a position of formal inferiority. A study of how a smaller state built room to manoeuvre out of language."
  },
  {
    "id": "a-christmas-far-from-home",
    "author": "Stanley Weintraub",
    "title": "A Christmas Far from Home",
    "url": "https://www.hachettebookgroup.com/titles/stanley-weintraub/a-christmas-far-from-home/9780306824135/?lens=hachette-books",
    "category": "Korean War",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9780306824135",
    "cover": "https://covers.openlibrary.org/b/isbn/9780306824135-L.jpg?default=false",
    "blurb": "Weintraub narrates the retreat from the Yalu over the winter of 1950, when the promise of being home by Christmas collapsed. Compact, and effective on the gap between headquarters optimism and the road south."
  },
  {
    "id": "famine-in-north-korea-markets-aid-and-reform",
    "author": "Stephan Haggard and Marcus Noland",
    "title": "Famine in North Korea: Markets, Aid, and Reform",
    "url": "https://cup.columbia.edu/book/famine-in-north-korea/9780231140010",
    "category": "North Korea: Society & Economy",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231140010",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231140010-L.jpg?default=false",
    "blurb": "Haggard and Noland's forensic account of the 1990s famine: how the food system failed, how aid was diverted, and how markets grew in the vacuum. The standard work, and the origin of much later analysis of the North Korean economy."
  },
  {
    "id": "witness-to-transformation-refugee-insights-into-north-korea",
    "author": "Stephan Haggard and Marcus Noland",
    "title": "Witness to Transformation: Refugee Insights into North Korea",
    "url": "https://cup.columbia.edu/book/witness-to-transformation/9780881324389",
    "category": "North Korea: Society & Economy",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780881324389",
    "cover": "https://covers.openlibrary.org/b/isbn/9780881324389-L.jpg?default=false",
    "blurb": "Built on large surveys of refugees in China and South Korea, this reconstructs the economy and social change from the testimony of people who lived it. Methodologically careful about what refugee samples can and cannot tell you."
  },
  {
    "id": "constructing-student-mobility-how-universities-recruit-stude",
    "author": "Stephanie K. Kim",
    "title": "Constructing Student Mobility: How Universities Recruit Students and Shape Pathways between Berkeley and Seoul",
    "url": "https://mitpress.mit.edu/9780262545143/constructing-student-mobility/",
    "category": "Diaspora & Migration",
    "publisher": "MIT Press",
    "source": "mitpress.mit.edu",
    "isbn": "9780262545143",
    "cover": "https://covers.openlibrary.org/b/isbn/9780262545143-L.jpg?default=false",
    "blurb": "Kim follows the pipeline between Seoul and Berkeley and shows how universities, agents and families jointly manufacture international student flows. A clear-eyed look at education as an export market."
  },
  {
    "id": "millennial-north-korea-forbidden-media-and-living-creatively",
    "author": "Suk-Young Kim",
    "title": "Millennial North Korea: Forbidden Media and Living Creatively with Surveillance",
    "url": "https://www.sup.org/books/asian-studies/millennial-north-korea",
    "category": "North Korea: Society & Economy",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9781503640870",
    "cover": "https://covers.openlibrary.org/b/isbn/9781503640870-L.jpg?default=false",
    "blurb": "Kim reads North Korean state media against interviews with defectors to examine the generation raised after the famine, on smuggled dramas and market money. Argues that generation is where the state's grip is loosest."
  },
  {
    "id": "without-you-there-is-no-us",
    "author": "Suki Kim",
    "title": "Without You, There Is No Us",
    "url": "https://www.penguinrandomhouse.com/books/207216/without-you-there-is-no-us-by-suki-kim/",
    "category": "Fiction & Memoir",
    "publisher": "Penguin Random House",
    "source": "penguinrandomhouse.com",
    "isbn": "9780307720665",
    "cover": "https://covers.openlibrary.org/b/isbn/9780307720665-L.jpg?default=false",
    "blurb": "Kim taught English to the sons of the elite at a Pyongyang university while reporting undercover. The ethics of that are debated; what the book captures about the students' isolation is hard to get any other way."
  },
  {
    "id": "the-sister-north-korea-s-kim-yo-jong-the-most-dangerous-woma",
    "author": "Sung-Yoon Lee",
    "title": "The Sister: North Korea's Kim Yo Jong, the Most Dangerous Woman in the World",
    "url": "https://www.hachettebookgroup.com/titles/sung-yoon-lee/the-sister/9781541704121/?lens=publicaffairs",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Hachette",
    "source": "hachettebookgroup.com",
    "isbn": "9781541704121",
    "cover": "https://covers.openlibrary.org/b/isbn/9781541704121-L.jpg?default=false",
    "blurb": "Lee's account of Kim Yo Jong's rise and her role in the regime's messaging and diplomacy. Written with a hard line on engagement, and clearest as a portrait of how power circulates inside the family."
  },
  {
    "id": "everyday-life-in-the-north-korean-revolution-1945-1950",
    "author": "Suzy Kim",
    "title": "Everyday Life in the North Korean Revolution, 1945–1950",
    "url": "https://www.cornellpress.cornell.edu/book/9781501705687/everyday-life-in-the-north-korean-revolution-19451950/",
    "category": "History & Empire",
    "publisher": "Cornell University Press",
    "source": "cornellpress.cornell.edu",
    "isbn": "9781501705687",
    "cover": "https://covers.openlibrary.org/b/isbn/9781501705687-L.jpg?default=false",
    "blurb": "Kim uses captured North Korean archives to reconstruct village life in the years before the war — land reform, literacy drives, women's organisations. It shows a revolution that had genuine participants before it hardened."
  },
  {
    "id": "this-kind-of-war-the-classic-korean-war-history-fiftieth-ann",
    "author": "T.R. Fehrenbach",
    "title": "This Kind of War: The Classic Korean War History, Fiftieth Anniversary Edition",
    "url": "https://www.nebraskapress.unl.edu/potomac/9781574883343/this-kind-of-war/",
    "category": "Korean War",
    "publisher": "University of Nebraska Press",
    "source": "nebraskapress.unl.edu",
    "isbn": "9781574883343",
    "cover": "https://covers.openlibrary.org/b/isbn/9781574883343-L.jpg?default=false",
    "blurb": "Fehrenbach's 1963 account, still read in American military circles for its argument that wars are won by infantry on the ground rather than technology. Dated in places, and enduringly influential."
  },
  {
    "id": "japan-south-korea-and-the-united-states-nuclear-umbrella",
    "author": "Terence Roehrig",
    "title": "Japan, South Korea, and the United States Nuclear Umbrella",
    "url": "https://cup.columbia.edu/book/japan-south-korea-and-the-united-states-nuclear-umbrella/9780231157995",
    "category": "Alliances & Regional Order",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231157995",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231157995-L.jpg?default=false",
    "blurb": "Roehrig examines what extended deterrence actually promises Seoul and Tokyo, and how much either capital believes it. The reference text for the credibility question now driving South Korea's nuclear debate."
  },
  {
    "id": "passcode-to-the-third-floor-an-insider-s-account-of-life-amo",
    "author": "Thae Yong-ho",
    "title": "Passcode to the Third Floor: An Insider's Account of Life Among North Korea's Political Elite",
    "url": "https://cup.columbia.edu/book/passcode-to-the-third-floor/9780231198868",
    "category": "Escape & Human Rights",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231198868",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231198868-L.jpg?default=false",
    "blurb": "Thae was North Korea's deputy ambassador in London before defecting, and writes from inside the diplomatic elite. Rare access to how the ruling circle talks to itself and manages the outside world."
  },
  {
    "id": "alignment-despite-antagonism-the-united-states-korea-japan-s",
    "author": "Victor Cha",
    "title": "Alignment Despite Antagonism: The United States-Korea-Japan Security Triangle",
    "url": "https://www.sup.org/books/politics/alignment-despite-antagonism",
    "category": "Alliances & Regional Order",
    "publisher": "Stanford University Press",
    "source": "sup.org",
    "isbn": "9780804731928",
    "cover": "https://covers.openlibrary.org/b/isbn/9780804731928-L.jpg?default=false",
    "blurb": "Cha's first book asks why Seoul and Tokyo cooperate at all given their history, and finds the answer in shared fear of American abandonment. The quasi-alliance argument that still frames how the triangle is analysed."
  },
  {
    "id": "the-black-box-demystifying-the-study-of-korean-unification-a",
    "author": "Victor Cha",
    "title": "The Black Box: Demystifying the Study of Korean Unification and North Korea",
    "url": "https://cup.columbia.edu/book/the-black-box/9780231558730",
    "category": "North Korea: Regime & Leadership",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231558730",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231558730-L.jpg?default=false",
    "blurb": "Cha takes on the methodological problem at the heart of the field: how to study a country that releases almost no reliable data. Part critique of how North Korea analysis is done, part proposal for doing it better."
  },
  {
    "id": "the-impossible-state",
    "author": "Victor Cha",
    "title": "The Impossible State",
    "url": "https://www.harpercollins.com/products/the-impossible-state-updated-edition-victor-cha?variant=32207276933154",
    "category": "North Korea: Regime & Leadership",
    "publisher": "HarperCollins",
    "source": "harpercollins.com",
    "isbn": "9780062906366",
    "cover": "https://covers.openlibrary.org/b/isbn/9780062906366-L.jpg?default=false",
    "blurb": "Cha's survey of North Korea's past and likely future, written with the authority of someone who negotiated with it. The updated edition is the standard one-volume introduction for the general reader."
  },
  {
    "id": "nuclear-north-korea",
    "author": "Victor Cha & David Kang",
    "title": "Nuclear North Korea",
    "url": "https://cup.columbia.edu/book/nuclear-north-korea/9780231189231",
    "category": "North Korea: Nuclear & Security",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231189231",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231189231-L.jpg?default=false",
    "blurb": "Cha and Kang debate each other in print — engagement against containment — chapter by chapter. Unusual and genuinely useful: you get both cases at full strength rather than a straw man."
  },
  {
    "id": "korea-a-new-history-of-south-and-north",
    "author": "Victor Cha & Ramon Pacheco Pardo",
    "title": "Korea: A New History of South and North",
    "url": "https://yalebooks.yale.edu/book/9780300278705/korea/",
    "category": "History & Empire",
    "publisher": "Yale University Press",
    "source": "yalebooks.yale.edu",
    "isbn": "9780300278705",
    "cover": "https://covers.openlibrary.org/b/isbn/9780300278705-L.jpg?default=false",
    "blurb": "Cha and Pacheco Pardo write the two Koreas as one story rather than two, from division to the present. The most current single-volume history covering both states together."
  },
  {
    "id": "a-misunderstood-friendship-mao-zedong-kim-il-sung-and-sino-n",
    "author": "Zhihua Shen and Yafeng Xia",
    "title": "A Misunderstood Friendship: Mao Zedong, Kim Il-sung, and Sino-North Korean Relations, 1949-1976",
    "url": "https://cup.columbia.edu/book/a-misunderstood-friendship/9780231200554",
    "category": "Alliances & Regional Order",
    "publisher": "Columbia University Press",
    "source": "cup.columbia.edu",
    "isbn": "9780231200554",
    "cover": "https://covers.openlibrary.org/b/isbn/9780231200554-L.jpg?default=false",
    "blurb": "Shen and Xia use Chinese and Soviet archives to show the Sino-North Korean relationship as far more mistrustful than the 'lips and teeth' slogan suggests. It reframes Pyongyang's most important partnership as a long negotiation between wary allies."
  }
];
